version: '3'

services:

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - backend

  webserver:
    image: nginx:alpine
    container_name: webserver
    command: nginx -g "daemon off;"
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - backend

  db:
     image: mysql:8.0
     container_name: db
     ports:
      - "3306:3306"
     volumes:
      - './docker/mysql/data:/var/lib/mysql'
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
       MYSQL_DATABASE: ${DB_DATABASE}
       MYSQL_USER: ${DB_USERNAME}
       MYSQL_PASSWORD: ${DB_PASSWORD}

     networks:
      - backend


networks:
  backend:
    driver: bridge
